FROM golang:1.23 AS build-stage

WORKDIR /api 

COPY go.mod go.sum ./
RUN go mod download 

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /app ./cmd/api/main.go


FROM gcr.io/distroless/base-debian11 

WORKDIR /

COPY --from=build-stage /app /app

EXPOSE 8080

ENTRYPOINT ["/app"]